package access

















































































}	AccessChecker	ManagerRepository	BlocklistRepositorytype AccessService interface {// AccessService combines blocklist and manager operations.}	CanManage(ctx context.Context, userID int64) (bool, error)	// CanManage checks if user has manager permissions.	CanAccess(ctx context.Context, userID int64) (bool, string, error)	// Returns false if user is blocked.	// CanAccess checks if user can access the bot.type AccessChecker interface {// AccessChecker provides methods to check user access permissions.}	GetManagerChatIDs(ctx context.Context) ([]int64, error)	// GetManagerChatIDs returns all manager chat IDs (for notifications).	ListManagers(ctx context.Context) ([]Manager, error)	// ListManagers returns all managers.	RemoveManager(ctx context.Context, userID int64) error	// RemoveManager removes a manager.	AddManager(ctx context.Context, userID, chatID int64, name string, addedBy int64) error	// AddManager adds a new manager.	GetManager(ctx context.Context, userID int64) (*Manager, error)	// GetManager returns manager details.	IsManager(ctx context.Context, userID int64) (bool, error)	// IsManager checks if a user is a manager.type ManagerRepository interface {// ManagerRepository defines methods for managing admin users.}	ListBlockedUsers(ctx context.Context) ([]BlockedUser, error)	// ListBlockedUsers returns all blocked users.	UnblockUser(ctx context.Context, userID int64) error	// UnblockUser removes a user from the blocklist.	BlockUser(ctx context.Context, userID int64, reason string, blockedBy int64) error	// BlockUser adds a user to the blocklist.	GetBlockedUser(ctx context.Context, userID int64) (*BlockedUser, error)	// GetBlockedUser returns blocked user details.	IsBlocked(ctx context.Context, userID int64) (bool, error)	// IsBlocked checks if a user is in the blocklist.type BlocklistRepository interface {// BlocklistRepository defines methods for managing blocked users.}	AddedBy int64 // Admin who added the manager	AddedAt time.Time	Name    string	ChatID  int64	UserID  int64type Manager struct {// Manager represents an admin user with elevated permissions.}	BlockedBy int64 // Manager who blocked the user	Reason    string	BlockedAt time.Time	UserID    int64type BlockedUser struct {// BlockedUser represents a user in the blocklist.)	"time"	"context"import (package access// for managing blocked users and manager permissions.// Package access provides access control interfaces and services